local c = require("utils.colors")
require("utils").set_hls({
	CursorLineNR = { fg = c.secondary },
	BufferOffset = { fg = c.secondary },
	FloatBorder = { bg = "None" },
	CursorLine = { bg = c.bg_highlight },
	ErrorMsg = { fg = c.red, bg = c.bg, underline = true },
	Float = { fg = c.red },
	Folded = { bg = c.invisible },
	Keyword = { fg = c.purple },
	Label = { fg = c.green },
	LineNr = { fg = c.comments },
	MatchParen = { fg = c.white, bg = c.comments },
	ModeMsg = { fg = "None", bg = "None" },
	NonText = { fg = c.invisibles, bg = c.bg },
	Number = { fg = c.orange },
	Search = { fg = c.bg, bg = c.secondary },
	SpecialComment = { fg = c.comments },
	SpecialKey = { fg = c.invisibles, bg = c.bg },
	StorageClass = { fg = c.purple },
	Tag = { fg = c.purple },
	Title = { fg = c.red },
	VertSplit = { fg = c.black, bg = c.black },
})
